import { Product, ProductCategory } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'oud-001',
    name: 'Royal Amber Oud',
    description: 'A majestic blend of rich amber and pure, aged oud wood. This fragrance evokes a sense of timeless luxury and power, perfect for special occasions and evening wear.',
    price: 250,
    imageUrl: 'https://picsum.photos/seed/oud1/800/800',
    scentProfile: ['Woody', 'Amber', 'Spicy', 'Warm'],
    category: 'perfume',
  },
  {
    id: 'oud-002',
    name: 'Mystic Rose Oud',
    description: 'An enchanting dance between the deep, smoky notes of oud and the delicate sweetness of Damask rose. A romantic and sophisticated scent that leaves a lasting impression.',
    price: 220,
    imageUrl: 'https://picsum.photos/seed/oud2/800/800',
    scentProfile: ['Floral', 'Woody', 'Smoky', 'Sweet'],
    category: 'perfume',
  },
  {
    id: 'oud-003',
    name: 'Saffron Leather Oud',
    description: 'A bold and charismatic fragrance combining the earthiness of oud with the exotic spice of saffron and the refined aroma of fine leather. For the confident and discerning individual.',
    price: 280,
    imageUrl: 'https://picsum.photos/seed/oud3/800/800',
    scentProfile: ['Leather', 'Spicy', 'Woody', 'Earthy'],
    category: 'perfume',
  },
  {
    id: 'oud-004',
    name: 'Celestial Citrus Oud',
    description: 'A surprisingly fresh take on oud. Bright top notes of bergamot and grapefruit give way to a sophisticated, woody base, creating a vibrant and uplifting experience.',
    price: 195,
    imageUrl: 'https://picsum.photos/seed/oud4/800/800',
    scentProfile: ['Citrus', 'Fresh', 'Woody', 'Uplifting'],
    category: 'perfume',
  },
  {
    id: 'oud-005',
    name: 'Midnight Vanilla Oud',
    description: 'A warm and comforting scent that wraps you in a blanket of creamy vanilla, rich oud, and a hint of tobacco. Seductive, cozy, and utterly addictive.',
    price: 235,
    imageUrl: 'https://picsum.photos/seed/oud5/800/800',
    scentProfile: ['Gourmand', 'Woody', 'Sweet', 'Warm'],
    category: 'perfume',
  },
  {
    id: 'oud-006',
    name: 'Pure Oud Essence Oil',
    description: 'For the true connoisseur. This is a 100% pure, ethically sourced oud oil, aged for over a decade. A complex, deeply spiritual scent that evolves on the skin.',
    price: 450,
    imageUrl: 'https://picsum.photos/seed/oud6/800/800',
    scentProfile: ['Pure Oud', 'Earthy', 'Animalic', 'Complex'],
    category: 'pure_oud',
  },
  {
    id: 'bakhoor-001',
    name: "Sultan's Bakhoor",
    description: "Rich, aromatic resin chips soaked in fragrant oils. When burned, they release a luxurious smoke that perfumes the home with traditional Middle Eastern scents.",
    price: 75,
    imageUrl: 'https://picsum.photos/seed/bakhoor1/800/800',
    scentProfile: ['Resin', 'Spicy', 'Sweet', 'Smoky'],
    category: 'bakhoor',
  },
  {
    id: 'powder-001',
    name: 'Sandalwood Oud Powder',
    description: 'A finely milled powder of pure oud and sandalwood. Ideal for gentle scenting of clothes, spaces, or for use in personal fragrance rituals.',
    price: 60,
    imageUrl: 'https://picsum.photos/seed/powder1/800/800',
    scentProfile: ['Powdery', 'Woody', 'Sandalwood', 'Subtle'],
    category: 'powder',
  },
  {
    id: 'gift-001',
    name: 'Oud Discovery Set',
    description: 'The perfect introduction to the world of oud. This gift set includes three of our most popular perfume vials, beautifully presented in a luxury gift box.',
    price: 150,
    imageUrl: 'https://picsum.photos/seed/gift1/800/800',
    scentProfile: ['Variety', 'Luxury', 'Gift'],
    category: 'gift_set',
  },
  {
    id: 'accessory-001',
    name: 'Artisan Mabkhara',
    description: 'A handcrafted ceramic incense burner (Mabkhara) designed for safely burning bakhoor or oud wood chips. An elegant addition to any home decor.',
    price: 95,
    imageUrl: 'https://picsum.photos/seed/accessory1/800/800',
    scentProfile: ['Ceramic', 'Handcrafted', 'Decorative'],
    category: 'accessory',
  },
  {
    id: 'oud-007',
    name: 'Royal Kyara LTD',
    description: 'An exceptionally rare and prized agarwood from Vietnam. Reserved for collectors, Kyara offers a sublime, multi-layered scent profile that is considered the pinnacle of oud.',
    price: 980,
    imageUrl: 'https://picsum.photos/seed/oud7/800/800',
    scentProfile: ['Rare', 'Complex', 'Spiritual', 'Kyara'],
    category: 'premium',
  },
];